# Generated by Django 5.2.11 on 2026-03-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0009_salesgoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='currency',
            field=models.CharField(blank=True, choices=[('XPF', 'XPF, Franc'), ('USD', 'USD, Dollar'), ('EUR', 'EUR, Euro'), ('GBP', 'GBP, Pound'), ('INR', 'INR, Rupee'), ('CAD', 'CAD, Dollar'), ('AUD', 'AUD, Dollar'), ('JPY', 'JPY, Yen'), ('CNY', 'CNY, Yuan'), ('CHF', 'CHF, Franc'), ('SGD', 'SGD, Dollar'), ('AED', 'AED, Dirham'), ('BRL', 'BRL, Real'), ('MXN', 'MXN, Peso')], max_length=3, null=True, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='lead_source',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('CALL', 'CALL'), ('EMAIL', 'EMAIL'), ('EXISTING CUSTOMER', 'EXISTING CUSTOMER'), ('PARTNER', 'PARTNER'), ('PUBLIC RELATIONS', 'PUBLIC RELATIONS'), ('CAMPAIGN', 'CAMPAIGN'), ('WEBSITE', 'WEBSITE'), ('GOUV_NC', 'Emploi Gouv NC'), ('PSUD', 'Province Sud'), ('JOB_NC', 'Job.nc'), ('LEMPLOI_NC', "L'Emploi.nc"), ('OTHER', 'OTHER')], max_length=255, null=True, verbose_name='Lead Source'),
        ),
    ]
