# Generated by Django 5.2.11 on 2026-03-18 03:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre',
                'verbose_name_plural': 'Paramètres',
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('template', models.TextField()),
                ('is_system', models.BooleanField(default=False, help_text='True = utilisé comme system prompt Ollama')),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de prompt',
                'verbose_name_plural': 'Templates de prompts',
            },
        ),
        migrations.CreateModel(
            name='RidetEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid7', models.CharField(db_index=True, max_length=20, unique=True)),
                ('denomination', models.CharField(blank=True, db_index=True, max_length=255)),
                ('sigle', models.CharField(blank=True, max_length=100)),
                ('enseigne', models.CharField(blank=True, db_index=True, max_length=255)),
                ('date_etablissement', models.DateField(blank=True, null=True)),
                ('commune', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('forme_juridique', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Établissement RIDET',
                'verbose_name_plural': 'Établissements RIDET',
            },
        ),
        migrations.CreateModel(
            name='ScrapeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('GOUV_NC', 'Emploi Gouv NC'), ('PSUD', 'Province Sud'), ('JOB_NC', 'Job.nc'), ('LEMPLOI_NC', "L'Emploi.nc")], max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'En cours'), ('SUCCESS', 'Succès'), ('PARTIAL', 'Partiel'), ('FAILED', 'Échoué')], default='RUNNING', max_length=20)),
                ('offers_imported', models.PositiveIntegerField(default=0)),
                ('offers_skipped', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Journal de scraping',
                'verbose_name_plural': 'Journaux de scraping',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('source', models.CharField(choices=[('GOUV_NC', 'Emploi Gouv NC'), ('PSUD', 'Province Sud'), ('JOB_NC', 'Job.nc'), ('LEMPLOI_NC', "L'Emploi.nc")], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('raw_description', models.TextField(blank=True)),
                ('rome_code', models.CharField(blank=True, max_length=10)),
                ('contract_type', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('experience_req', models.CharField(blank=True, max_length=100)),
                ('education_req', models.TextField(blank=True)),
                ('qualification', models.CharField(blank=True, max_length=100)),
                ('nb_postes', models.PositiveSmallIntegerField(default=1)),
                ('url_external', models.URLField(blank=True, max_length=500)),
                ('skills_json', models.JSONField(blank=True, default=list)),
                ('activities_json', models.JSONField(blank=True, default=list)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NEW', 'Nouvelle'), ('PUBLIEE', 'Publiée'), ('ARCHIVEE', 'Archivée')], default='NEW', max_length=50)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('rid7', models.CharField(blank=True, db_index=True, max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
                'ordering': ['-date_published'],
                'indexes': [models.Index(fields=['source', 'external_id'], name='iod_job_int_source_ce1a80_idx'), models.Index(fields=['rid7'], name='iod_job_int_rid7_49b592_idx'), models.Index(fields=['status', 'score'], name='iod_job_int_status_082356_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid7', models.CharField(blank=True, db_index=True, max_length=20)),
                ('analysis_type', models.CharField(choices=[('skill_analysis', 'Analyse compétences'), ('offer_diagnostic', 'Diagnostic offre'), ('questions_offre', 'Questions brûlantes (offre)'), ('questions_company', 'Questions brûlantes (entreprise)'), ('email_job', 'Email prospection (offre)'), ('email_general', 'Email prospection (général)'), ('ice_breaker', 'Ice breaker')], max_length=50)),
                ('model_used', models.CharField(max_length=100)),
                ('prompt_hash', models.CharField(db_index=True, max_length=64)),
                ('result_text', models.TextField(blank=True)),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('language', models.CharField(default='Français', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='iod_job_intel.joboffer')),
            ],
            options={
                'verbose_name': 'Analyse IA',
                'verbose_name_plural': 'Analyses IA',
                'indexes': [models.Index(fields=['job_offer', 'analysis_type'], name='iod_job_int_job_off_491de8_idx'), models.Index(fields=['rid7', 'analysis_type'], name='iod_job_int_rid7_397482_idx')],
            },
        ),
    ]
