# Generated by Django 5.2.11 on 2026-03-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iod_job_intel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='external_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='joboffer',
            unique_together={('external_id', 'source')},
        ),
    ]
