# Generated by Django 5.2.11 on 2026-03-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iod_job_intel', '0003_seed_ai_model_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridetentry',
            name='activite_principale',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ridetentry',
            name='adresse',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ridetentry',
            name='code_naf',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='ridetentry',
            name='dirigeants',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
