# Generated by Django 5.2.11 on 2026-03-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iod_job_intel', '0004_ridetentry_activite_principale_ridetentry_adresse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Code interne (ex: JOB_NC). Correspond à JobOffer.source.', max_length=20, unique=True)),
                ('label', models.CharField(help_text='Libellé affiché (ex: Job.nc)', max_length=100)),
                ('url', models.URLField(blank=True, help_text='URL du site source (ex: https://www.job.nc)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Source d'offres d'emploi",
                'verbose_name_plural': "Sources d'offres d'emploi",
                'ordering': ('label',),
            },
        ),
        migrations.AddField(
            model_name='ridetentry',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
