# Generated by Django 5.2.11 on 2026-03-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iod_job_intel', '0009_seed_classify_offer_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridetentry',
            name='activite_principale',
            field=models.TextField(blank=True),
        ),
    ]
